### ISSUE TITLE
[BUG] Wrong lab's number in SEC588

### ISSUE THREAD

**Issue by MrMoshkovitz** [dhondta/tex-course-index#1]
All of the lab's Number in SEC588  does not fit to the actual book.

### **Lab 1.1: Getting Started:** 12-24
![Lab1_1](https://user-images.githubusercontent.com/50079480/163225351-6784eba5-2d8e-4c29-90d9-92f8926febea.jpeg)

### **Lab 1.2: Domain Discovery Labs Workbook Pages:**
![Lab1_2](https://user-images.githubusercontent.com/50079480/163225328-30114968-63f3-49bc-b774-13131c73cb53.png)

### **Lab 1.3:  Workbook Pages:**
![Lab1_3](https://user-images.githubusercontent.com/50079480/163225415-baef136d-3ec4-4dcb-9f8c-df90ffc07e1c.jpeg)

Please Also add some documentation, I've tried to rebuild it correctly but the build execution was not successfully

**Comment by dhondta** [comment]
Hi @MrMoshkovitz 
Thank you for mentioning this.
Actually, this is not a matter of wrong page number, this is related to the version, `SEC588_W_G01_01`. I checked in my books and the page number are right. Beware however that this may be misleading but this version dates from beginning of 2021 while I mention `11/2021` in my index, which is November, when I passed the exam.

**Comment by dhondta** [comment]
@MrMoshkovitz  If you adapted the index for the latest version, you can of course submit your `.pdf` and `.idx` for fixing this.

**Comment by MrMoshkovitz** [comment]
As mentioned Above, I was unable to build the index so I haven't done this.

But I did used this Index to create my Own Colorfull Index in XLSX.

I'll upload it when it will be done

**Comment by dhondta** [comment]
@MrMoshkovitz 
- The file structure for building the index is detailed on the [README](https://github.com/dhondta/tex-course-index-template#card_file_box-structure).
- The build command is given on the [README](https://github.com/dhondta/tex-course-index-template#gear-compilation).
- The way for making the index is explained on the [README](https://github.com/dhondta/tex-course-index-template#bookmark_tabs-making-your-index).

If it is not clear, can you point out where the explanations should be refined ?
Moreover, you do not mention any error, you just tell *I've tried to rebuild it correctly but the build execution was not successfully*. What am I supposed to do with this ?
Beware that if you used `sec588.idx`, given the file tructure detailed on the [README](https://github.com/dhondta/tex-course-index-template#card_file_box-structure), you need to rename the file to `main.idx` before trying to compile.

PS : Glad `sec558.pdf` still helped you make your XLSX index !
