### ISSUE TITLE
Makeindex issue

### ISSUE THREAD

**Issue by flomch96** [dhondta/tex-course-index#4]
Hi @dhondta
Error : could not start the command : makeindex "main".idx -s lib/std.ist
Thank you for your response on the other issue.
I am using a windows OS. Do you know where i can find the full path of the makeindex command?
Thank you

**Comment by dhondta** [comment]
Hi @flomch96 
I don't use TeXmaker on Windows but I guess this may be something like `C:\Program Files\TeXmaker\bin\makeindex.exe`.
Please check and then adapt your "Quick Build" command in the options of TeXmaker. If you need more help, I suggest you contact the maintainers of TeXmaker and/or that you check their documentation.

**Comment by flomch96** [comment]
Thanks @dhondta problem solved
