### ISSUE TITLE
Incorrect consolidation of page numbers by book

### ISSUE THREAD

**Issue by camlischke1** [dhondta/tex-course-index#5]
I have an issue with the compiler outputted a book name/identifier with every set of page numbers instead of consolidating. I am using the default .ist file given. the only thing I have changed is the preamble for the book. Instead of a course code, I just have it prepend "B" to the book number. 

Reproduce:
1. Add the following to the .idx file
`
\indexentry{1@behavioral analysis|book{1}}{92}
`
`
\indexentry{1@behavioral analysis|book{1}}{94}
`
`
\indexentry{1@behavioral analysis|book{1}}{88}
`
2. Compile with given command

3. See output. My book preamble appears for each page number.
![image](https://github.com/academic-templates/tex-course-index-template/assets/61704172/85159735-d78c-4712-b1a6-9c2d5967dda6)

DESIRED OUTPUT
behavioral analysis.....................B1 - 88, 92, 94

**Comment by dhondta** [comment]
Hi @camlischke1 

You shall use the following : 
```
\indexentry{1@behavioral analysis|book{1}}{92}
\indexentry{1@behavioral analysis}{94}
\indexentry{1@behavioral analysis}{88}
```

I know it may look dirty, but it is the way Makeindex processes entries.
